### ISSUE TITLE
首页报错

### ISSUE THREAD

**Issue by 0x01x0** [gogobody/onecircle#14]
syntax error, unexpected end of file
ParseError: syntax error, unexpected end of file in /opt/typecho/usr/themes/onecircle/includes/post-pagination.php:47
Stack trace:
#0 /opt/typecho/usr/themes/onecircle/index.php(90): Widget_Archive->need('includes/post-p...')
#1 /opt/typecho/var/Widget/Archive.php(2049): require_once('/opt/typecho/us...')
#2 /opt/typecho/var/Typecho/Router.php(138): Widget_Archive->render()
#3 /opt/typecho/index.php(23): Typecho_Router::dispatch()
#4 {main}

环境 php7.3 MariaDB Debian10

**Comment by 0x01x0** [comment]
已经找到问题所在 打扰了！

**Comment by 0x01x0** [comment]
根据 [#1](https://github.com/gogobody/onecircle/issues/1)无法解决问题

**Comment by gogobody** [comment]
没有这个测试环境。。。

**Comment by wangcong099878** [comment]
这个需要php8支持吗

**Comment by gogobody** [comment]
> 这个需要php8支持吗

不需要

**Comment by roche1990** [comment]
same: syntax error, unexpected end of file
